### ISSUE TITLE
Put package dependencies separate from the playbook tasks

### ISSUE THREAD

**Issue by hakamine** [artefactual-labs/ansible-archivematica-src#7]
- Instead of putting the package dependencies in the playbook itself, move to a separate file, or 
- Put the dependencies in a file in the archivematica repo, and make it possible for the ansible playbook to read this file

**Comment by sevein** [comment]
fe6619 added libffi-dev and libssl-dev so the archivematica-storage-service virtualenv builds, just a temporary solution.

**Comment by jhsimpson** [comment]
libssl-dev is a dependency of the dashboard and the storage service.  RIght now libssl-dev appears to only get installed as a storage service dependency.  If the storage service is not installed on the same machine as the dashboard, the dashboard install fails because of this missing dependency.

**Comment by sevein** [comment]
We've been doing this for a while and it's working. In `stable/1.6.x` there is a mix of the old and the new approach, but `qa/1.7.x` relies exclusively on the osdeps files that live in the AM and SS repos. The structure of these files may be improvable (suggestions are welcome) but I think this issue is not relevant anymore.
